source "https://rubygems.org"

gem "rails", "~> 7.2.3", ">= 7.2.3.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "aws-sdk-s3"
gem "sneakers"
gem "openai"
gem "pdf-reader"
gem "matrix"
gem "prawn"
gem "prawn-table"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails", "~> 7.0"
  gem "factory_bot_rails"
  gem "simplecov", require: false
  gem "simplecov-console", require: false
  gem "simplecov-json", require: false
  gem "faker"
end
